# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpCoreProtoElements.proto

require 'google/protobuf'


descriptor_data = "\n\x19SpCoreProtoElements.proto\x12\x0fz9.spcore.proto\"+\n\x0e\x42igIntegerData\x12\x0f\n\x05\x62ytes\x18\x01 \x01(\x0cH\x00\x42\x08\n\x06\x62ytes_\"X\n\x0bSqlDateData\x12\x0e\n\x04year\x18\x01 \x01(\x05H\x00\x12\x0f\n\x05month\x18\x02 \x01(\x05H\x01\x12\r\n\x03\x64\x61y\x18\x03 \x01(\x05H\x02\x42\x07\n\x05year_B\x08\n\x06month_B\x06\n\x04\x64\x61y_\"`\n\x0bSqlTimeData\x12\x0e\n\x04hour\x18\x01 \x01(\x05H\x00\x12\x10\n\x06minute\x18\x02 \x01(\x05H\x01\x12\x10\n\x06second\x18\x03 \x01(\x05H\x02\x42\x07\n\x05hour_B\t\n\x07minute_B\t\n\x07second_\"+\n\x0c\x44\x61teTimeData\x12\x10\n\x06millis\x18\x01 \x01(\x03H\x00\x42\t\n\x07millis_B\x02H\x03\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Z9
  module Spcore
    module Proto
      BigIntegerData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("z9.spcore.proto.BigIntegerData").msgclass
      SqlDateData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("z9.spcore.proto.SqlDateData").msgclass
      SqlTimeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("z9.spcore.proto.SqlTimeData").msgclass
      DateTimeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("z9.spcore.proto.DateTimeData").msgclass
    end
  end
end
